### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by farisfaikar**
#### Issue: #16
Added detailed instructions on how to install and run the program

### CODE REVIEW

**Comment by TechWiz-3** [comment]
Great work however why did you put installing `requirements.txt`? This is already taken care of as part of the pip installation in `setup.py`

**Comment by farisfaikar** [comment]
Okay, I will remove the ```pip install -r requirements.txt``` instruction

**Comment by TechWiz-3** [comment]
Ok so now you've removed `requirements.txt`, is there any need for `git clone` for the average user?

**Comment by farisfaikar** [comment]
```git clone``` will be required if you would like to contribute to the repo. However, no it won't be required for the average user, so I will remove them as well.

**Comment by TechWiz-3** [comment]
Perfecto, thank you

**Comment by farisfaikar** [comment]
Could you please label this as hacktoberfest-accepted? Love your work, thank you!

**Pull request merged**
