### PR TITLE
added --forks args and updated README.md

### PR DESCRIPTION
**Pull request by erdepe-dad**
added optional args forks. example usage:
```
scout --forks
```
it'll show forks on the results:
show_forks_option

### CODE REVIEW

**Comment by erdepe-dad** [comment]
#26 Please Review this Pull Request @TechWiz-3 . Thanks

**Comment by erdepe-dad** [comment]
if forks args doesn't include in command it'll hide forks from results:
```
scout --standard
```
Screen Shot 2022-10-18 at 19 23 32
also show the help:
Screen Shot 2022-10-18 at 19 23 13

**Comment by TechWiz-3** [comment]
Thanks a lot 🔥 
This is great work, I really appreciate that you bumped the version and added a screenshot as well 👍

**Comment by erdepe-dad** [comment]
My Pleasure 🙏

**Pull request merged**
