### PR TITLE
No-colors version 

### PR DESCRIPTION
**Pull request by Manoj0Marmat**
Signed-off-by: Manoj Marmat <manojrajput762000@gmail.com>

Issue #3 
Screen Recording 2022-10-09 at 12 40 58 AM

### CODE REVIEW

**Comment by Manoj0Marmat** [comment]
@TechWiz-3 hii it's working 👍🏻 i've added no color feature please review it

**Comment by TechWiz-3** [comment]
Thanks a lot for your work and perseverance, really appreciate that 🙏 

I have made some minor changes in https://github.com/TechWiz-3/scout/pull/34/commits/6fa1771ec0a2f03f3ddf10e9a738c33074903344 if you are interested

**Comment by Manoj0Marmat** [comment]
> Thanks a lot for your work and perseverance, really appreciate that 🙏
> 
> I have made some minor changes in [6fa1771](https://github.com/TechWiz-3/scout/commit/6fa1771ec0a2f03f3ddf10e9a738c33074903344) if you are interested

thanks i learned a lot ❤️🌹

**Comment by TechWiz-3** [comment]
really glad to hear that 😊

**Pull request merged**
