### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Akash190104**
Fixed a typo. @ahmadsyafrudin Please review.

### CODE REVIEW

**Comment by erdepe-dad** [comment]
~~Looks Good to me, I'm Okay wit that 👍 @Akash190104~~
Sorry @Akash190104 , I'm Not the Owner of the Project. Please Contact Maintainer or Repo's Owner.

**Comment by erdepe-dad** [comment]
I cant Merge this PR. Please @TechWiz-3 Need More reviewer for this. Thanks 🙏🏻

**Comment by V3ntus** [comment]
Some rando actually pretended to merge this

**Review by V3ntus — CHANGES_REQUESTED** [review]
No

**Comment by TechWiz-3** [comment]
Nah i think it's coz the last commit on the repos from ahmad, he thought ahmad is the repo owner

**Comment by V3ntus** [comment]
That's now how Git works 😭

**Comment by TechWiz-3** [comment]
Thanks for the contribution bro, @Akash190104 but the whole PR is just an extra comma, i don't think that really warrants a pull request, also the comma position itself doesn't really make sense. I appreciate wanting to contribute to hacktoberfest but please ensure your pull requests contain actual improvements.

You can find tasks to work on in a repositories [Issues](https://github.com/TechWiz-3/scout/issues) tab :)

**Comment by TechWiz-3** [comment]
> That's now how Git works 😭

true, but the owner name is at the top left tho lol

issok, i was a beginner myself not long ago - still am maybe 🤣

**Comment by erdepe-dad** [comment]
haha, Same here. Lifetime Learner I am. Always Newbie Everyday.

**Comment by erdepe-dad** [comment]
> Some rando actually pretended to merge this

haha, I'm not a rando and pretended to merge this. thats why i'm Mention TechWiz about this. I'm just a passer-by. 
😬
🙏🏻

**Comment by TechWiz-3** [comment]
All good brother, it was a weird situation 🤣

**Comment by erdepe-dad** [comment]
no worries bro. 🤣

**Pull request closed without merging**
