### PR TITLE
No-colors version

### PR DESCRIPTION
**Pull request by Manoj0Marmat**
Signed-off-by: Manoj Marmat <manojrajput762000@gmail.com>

Issue #3 
Screen Recording 2022-10-09 at 12 40 58 AM

### CODE REVIEW

**Comment by Manoj0Marmat** [comment]
@TechWiz-3 issue fixed please review it

**Comment by Manoj0Marmat** [comment]
@TechWiz-3 in first approach i was using lot of if else condition to change colors that was worst approach to do that now i came up into another solution of Dict please review it i think this is a best way to add dynamic colors combination

**Comment by Manoj0Marmat** [comment]
@TechWiz-3 please review it

**Comment by Manoj0Marmat** [comment]
@TechWiz-3 did you review it ?

**Comment by Manoj0Marmat** [comment]
@TechWiz-3 resolved conflict please check

**Comment by TechWiz-3** [comment]
Hey brother, sorry it took me so long to respond 😅 

Thank you for your work. Your solution in this PR is quite nice however it is probably best used for a much larger project. As Scout currently, is quite small I prefer your solution in your main branch.

In the future we may implement this solution but for now I will close this PR, please open another one merging your main instead of `feat-nocolor` and I will merge it 👍

**Comment by Manoj0Marmat** [comment]
> Hey brother, sorry it took me so long to respond 😅
> 
> Thank you for your work. Your solution in this PR is quite nice however it is probably best used for a much larger project. As Scout currently, is quite small I prefer your solution in your main branch.
> 
> In the future we may implement this solution but for now I will close this PR, please open another one merging your main instead of `feat-nocolor` and I will merge it 👍

agreed 👍

**Comment by Manoj0Marmat** [comment]
@TechWiz-3 i'm getting error with new update 
Screenshot 2022-10-12 at 4 48 15 PM

**Comment by TechWiz-3** [comment]
Hmm that probably means merge conflicts weren't fixed properly. Can you pull from the main branch again?

**Comment by Manoj0Marmat** [comment]
Yes I did but getting same error

**Comment by TechWiz-3** [comment]
how about if you clone this repo and try the same command? 😮 

the error doesn't make any sense, if you find no error from the clone of my repo then we'll know it's a merge issue, if not, then it's an issue with my code

**Comment by Manoj0Marmat** [comment]
K

**Comment by TechWiz-3** [comment]
any updates man?

**Pull request closed without merging**
