### PR TITLE
No-colors version

### PR DESCRIPTION
**Pull request by Manoj0Marmat**
adding new args --nocolor to get default color table

Issue #3 

Screen Recording 2022-10-08 at 2 50 22 PM

### CODE REVIEW

**Comment by Manoj0Marmat** [comment]
@TechWiz-3 we can't use --no-color args we because - not allowed we can only use --nocolor

**Comment by Manoj0Marmat** [comment]
@TechWiz-3 please review it

**Comment by TechWiz-3** [comment]
Perfect and thanks for the screen recording, makes it much easier.

Can you please remove the color in the input prompts at the beginning as well please?

**Comment by Manoj0Marmat** [comment]
Sure

**Comment by Manoj0Marmat** [comment]
@TechWiz-3 
Screen Recording 2022-10-08 at 4 53 44 PM
 input prompts color fix

**Comment by Manoj0Marmat** [comment]
@TechWiz-3 please review it

**Comment by TechWiz-3** [comment]
This great and i was ready to merge but i noticed that some of the more recent updates aren't reflected in the code, it looks like you pulled from my repo but your local version was older so when you pushed to your repo you overwrote the new changes.

You'll notice that in your version `BASE_URL` is from yesterday's version which was fixed recently and the `print_welcome_message` function was also removed
Screen Shot 2022-10-08 at 10 42 08 pm

**Comment by Manoj0Marmat** [comment]
yes working on it i also noticed that

**Comment by TechWiz-3** [comment]
🙏

**Pull request closed without merging**
