### PR TITLE
Added small feature that show Number of Forks, Stars and Contributor in README.md

### PR DESCRIPTION
**Pull request by Shadowpii**

### CODE REVIEW

**Comment by TechWiz-3** [comment]
I like this however could you please change the badge style to `flat-square`

**Comment by TechWiz-3** [comment]
Thank you :), note that `flat-square` refers to the style name, not `for-the-badge`. I fixed that myself 👍 

Fun fact: my first PR was adding badges to a repo, I think it's a nice choice because you're adding value without getting too technical. I'd recommend you look into adding icons and colors to the badges as you go along

**Comment by Shadowpii** [comment]
Thanks I will try to be better next time. It was great to know for me as a beginner about your experience. Thanks

**Comment by TechWiz-3** [comment]
❤️ :)

**Pull request merged**
