### PR TITLE
Fixed Except Keyboard Interrupt for inputs

### LINKED ISSUE #7: Except Keyboard Interrupt for inputs
Currently, when getting user inputs, if the user interrupts the prompts with `Ctrl-C`, the standard `KeyboardInterrupt` message occurs!

In the `get_url()` function add an exception for KeyboardInerrupt and put a nice message like *Farewell my friend, beware the crickets*. Then print a new line to the console and exit.

Screen Shot 2022-10-08 at 11 56 22 am

### PR DESCRIPTION
**Pull request by Kiinitix**
Just let me know if this is fine or not.

Fix #7

### CODE REVIEW

**Comment by TechWiz-3** [comment]
1. Please group the console.input statements together
2. Have the if statements that set the url building variables **outside** the `try` statement, in an `else` statement
3. When the `except` is triggered, you must import sys and do `sys.exit(1)`, otherwise the program will just continue

**Comment by TechWiz-3** [comment]
Also for the future, if you're solving an issue, remember to reference it in the PR :)

**Comment by Kiinitix** [comment]
I'm not exactly getting your 1st and 2nd points. Do I need to keep all the console.input statements inside the try block and shift all the if-else and return statements to else block?

**Comment by TechWiz-3** [comment]
> Do I need to keep all the console.input statements inside the try block and shift all the if-else and return statements to else block?

Yes exactly 👍 just to be a little cleaner for future development

**Comment by Kiinitix** [comment]
Is it fine now?

**Comment by TechWiz-3** [comment]
Number 1 and 2 are perfect now but remember number 3 ;)

> 3. When the `except` is triggered, you must import sys and do `sys.exit(1)`, otherwise the program will just continue

If you test your code locally you'll see that the code will continue, so you need to exit the program when a keyboard interrupt occurs

**Comment by Kiinitix** [comment]
So sorry for not implementing that. It just slipped from my mind. Is it fine now?

**Comment by TechWiz-3** [comment]
Issok man all good, this is perfect, thanks for your work

**Comment by Kiinitix** [comment]
Thank you, I  learned something new today.

**Comment by Kiinitix** [comment]
Sorry, but can you please add the hacktoberfest accepted label here. It's currently not being counted in the hacktoberfest.

**Comment by TechWiz-3** [comment]
OK, that's weird

**Comment by Kiinitix** [comment]
Screenshot (390)

**Comment by TechWiz-3** [comment]
Hmm `not-accepted` isn't in any of the official [exceptions](https://hacktoberfest.com/participation/#pr-mr-details) maybe it's a lag on github's side?

**Comment by Kiinitix** [comment]
It's accepted now. Thank you.

**Comment by TechWiz-3** [comment]
☺️

**Pull request merged**
